---
abstract: 'DateTime Wrappers for PGObject'
author:
  - 'Chris Travers <chris.travers@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PGObject-Type-DateTime
no_index:
  directory:
    - t
    - inc
requires:
  DateTime: 0
  DateTime::TimeZone: 0
  PGObject: 1.3
version: v1.00.001
